apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
      tier: proxy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        release: {{ .Release.Name }}
        tier: proxy
    spec:
      serviceAccountName: {{ .Release.Name }}
      automountServiceAccountToken: false
      containers:
        - name: {{ .Release.Name }}
          image: gcr.io/cloudsql-docker/gce-proxy:{{ .Values.version }}
          securityContext:
            runAsUser: 2
            runAsGroup: 2
            privileged: false
            allowPrivilegeEscalation: false
          command:
            - /cloud_sql_proxy
            - -verbose=false
            - -log_debug_stdout=true
            - --dir=/cloudsql
            - -instances={{ .Values.dbInstance }}=tcp:{{ .Values.dbPort }}
            - -credential_file=/secrets/cloudsql/{{ regexFind "[a-zA-Z]*$" .Values.secret }}
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: {{ regexReplaceAll "\\.[a-zA-Z]*$" .Values.secret "" }}
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
