apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taito:status-viewer
  labels:
    taito.dev/aggregate-to-developers: "true"
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taito:secret-viewer
  labels:
    taito.dev/aggregate-to-developers: "true"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taito:pod-killer
  labels:
    taito.dev/aggregate-to-developers: "true"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taito:pod-executer
  labels:
    taito.dev/aggregate-to-developers: "true"
rules:
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taito:pod-portforwarder
  labels:
    taito.dev/aggregate-to-developers: "true"
rules:
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taito:deployer
  labels:
    taito.dev/aggregate-to-developers: "true"
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taito:developer
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      taito.dev/aggregate-to-developers: "true"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taito:iam-admin
rules:
- apiGroups: [""]
  resources: ["roles", "rolebindings"]
  verbs: ["*"]
